# Generated by Django 5.0.6 on 2026-08-03 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category', models.CharField(blank=True, help_text='e.g. Analgesic, Antibiotic', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(db_index=True, max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('is_generic', models.BooleanField(db_index=True, default=False)),
                ('strength', models.CharField(blank=True, help_text='e.g. 500mg', max_length=50)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream/Ointment'), ('drops', 'Drops'), ('other', 'Other')], default='tablet', max_length=20)),
                ('salt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='catalog.salt')),
            ],
            options={
                'indexes': [models.Index(fields=['salt', 'is_generic'], name='catalog_med_salt_id_d0e226_idx')],
            },
        ),
    ]
