# Generated by Django 5.0.6 on 2026-08-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salt',
            name='info_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salt',
            name='usage_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salt',
            name='usage_purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
