# Generated by Django 5.0.6 on 2026-08-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_pharmacyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='closes_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='is_24_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='opens_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
