# Generated by Django 5.0.6 on 2026-08-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_pharmacy_closes_at_pharmacy_is_24_7_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='backend_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
