# Generated by Django 5.0.6 on 2026-08-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='google_sub',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
